# Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4]

# # Controller to control end effector joints
# hand_ee_controller:
#   type: "position_controllers/JointTrajectoryController"
#   joints: []

# Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50